FROM ubuntu as builder

WORKDIR /opt

RUN apt update && \
    apt install unzip -y

COPY target/universal .

RUN unzip chirper-api-*.zip -d build && \
    mv build/chirper-api* chirper-api

FROM openjdk:8-jdk-slim

ARG git_commit
ARG git_branch
ARG build_timestamp

ENV GIT_COMMIT $git_commit
ENV GIT_BRANCH $git_branch
ENV DOCKER_BUILD_TIMESTAMP $build_timestamp

WORKDIR /opt/chirper-api

COPY --from=builder /opt/chirper-api .

EXPOSE 9000

ENTRYPOINT ["bash"]

CMD ["/opt/chirper-api/bin/chirper-api"]
