version: "3"

services:
  user-service:
    build:
      dockerfile: user-service/Dockerfile
      context: .
    tty: true
    command: "runWithPostgresql"
    ports:
      - 9000:9000
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/chirper-api"
      - "/opt/chirper-api/project/target"
      - "/opt/chirper-api/user-service/target"
      - "/opt/chirper-api/shared/target"
      - "/opt/chirper-api/macros/target"
      - "/root/.sbt/1.0/plugins"
      - "~/.aws:/root/.aws"
    environment:
      POSTGRESQL_URL: "jdbc:postgresql://postgresql-database:5432/user-service"
      POSTGRESQL_USER: "my-user"
      POSTGRESQL_PASSWORD: "password"

  postgresql-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "user-service"
      POSTGRES_USER: "my-user"
      POSTGRES_PASSWORD: "password"

