version: "3"

services:
  user-service:
    build: .
    tty: true
    command: userServiceWithPostgresql
    depends_on:
      - postgresql-database
      - kafka-broker
      - schema-registry
    ports:
      - 9000:9000
      - 5005:5005
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - "~/.aws:/root/.aws"
      - ".:/opt/chirper-api"
      - "/opt/chirper-api/project/target"
      - "/opt/chirper-api/user-service/target"
      - "/opt/chirper-api/shared/target"
      - "/opt/chirper-api/macros/target"
      - "/root/.sbt/1.0/plugins"
    environment:
      POSTGRESQL_URL: "jdbc:postgresql://postgresql-database:5432/user-service"
      POSTGRESQL_USER: "my-user"
      POSTGRESQL_PASSWORD: "password"
      KAFKA_BOOTSTRAP_SERVERS: "kafka-broker:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      DEV_MODE: "DockerCompose"

  email-service:
    build: .
    command: emailService/run
    depends_on:
      - schema-registry
      - kafka-broker
    volumes:
      - "~/.sbt:/root/.sbt"
      - "~/.ivy2:/root/.ivy2"
      - ".:/opt/chirper-api"
      - "/opt/chirper-api/project/target"
      - "/opt/chirper-api/macros/target"
      - "/opt/chirper-api/shared/target"
      - "/opt/chirper-api/email-service/target"
      - "/root/.sbt/1.0/plugins"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka-broker:9092"
      SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      SENDGRID_API_KEY: "N/A"

  postgresql-database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "user-service"
      POSTGRES_USER: "my-user"
      POSTGRES_PASSWORD: "password"

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: "2181"

  kafka-broker:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:9092"

  schema-registry:
    image: confluentinc/cp-schema-registry
    depends_on:
      - zookeeper
    ports:
      - 8081:8081
    environment:
      SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: "zookeeper:2181"

  schema-registry-ui:
    image: landoop/schema-registry-ui
    depends_on:
      - schema-registry
    ports:
      - 8000:8000
    environment:
      SCHEMAREGISTRY_URL: "http://schema-registry:8081"
      PROXY: "true"



