apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chirper
  name: chirper-api-{{{ branch }}}-deployment
spec:
  selector:
    matchLabels:
      app: chirper-api-{{{ branch }}}
  replicas: 1
  template:
    metadata:
      labels:
        app: chirper-api-{{{ branch }}}
    spec:
      containers:
        - name: chirper-api-{{{ branch }}}
          image: {{{ dockerImage }}}
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: chirper-api-{{{ branch }}}-config-map
          livenessProbe:
            httpGet:
              port: 9000
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5

