apiVersion: v1
kind: ConfigMap
metadata:
  namespace: chirper-{{ git_branch }}
  name: user-service-config-map
data:
{% for key, value in config_values.items() %}
  {{ key }}: {{ value }}
{% endfor %}
