apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: chirper-{{ git_branch }}
  name: user-service-deployment
spec:
  selector:
    matchLabels:
      app: user-service
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service-container
          image: {{ docker_image }}
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: user-service-config-map
          env:
{% for key, value in secrets.items() %}
            - name: {{ key }}
              valueFrom:
                secretKeyRef:
                  name: user-service-secrets
                  key: {{ key }}
{% endfor %}
          livenessProbe:
            httpGet:
              port: 9000
              path: /health
            initialDelaySeconds: 15
            periodSeconds: 5

