apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: chirper-{{ git_branch }}
  name: user-service-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: user-service-tls
      hosts:
        - {{ git_branch }}.chirper-user.ruchij.com
  rules:
    - host: {{ git_branch }}.chirper-user.ruchij.com
      http:
        paths:
          - backend:
              serviceName: user-service
              servicePort: 9000
