apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: chirper-{{{ branch }}}
  name: user-service-tls-certificate
spec:
  secretName: user-service-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - {{{ branch }}}.chirper-user.ruchij.com
  acme:
    config:
      - dns01:
          provider: route53-dns
        domains:
          - {{{ branch }}}.chirper-user.ruchij.com
