---
- hosts: localhost
  connection: local
  vars:
    secrets:
      KAFKA_USERNAME: '{{ lookup("aws_ssm", "/chirper-api/kafka/username") }}'
      KAFKA_PASSWORD: '{{ lookup("aws_ssm", "/chirper-api/kafka/password") }}'
      SCHEMA_REGISTRY_USERNAME: '{{ lookup("aws_ssm", "/chirper-api/schema-registry/username") }}'
      SCHEMA_REGISTRY_PASSWORD: '{{ lookup("aws_ssm", "/chirper-api/schema-registry/password") }}'
      SENDGRID_API_KEY: '{{ lookup("aws_ssm", "/chirper-api/sendgrid/api-key") }}'
  tasks:
    - name: Delete existing set-secrets.sh
      file:
        path: set-secrets.sh
        state: absent

    - name: Create new set-secrets.sh file
      copy:
        dest: set-secrets.sh
        content: "#!/usr/bin/env bash"

    - lineinfile:
        dest: set-secrets.sh
        line: "export {{ item.key }}={{ item.value }}"
      with_items: "{{ secrets | dict2items }}"
